In [46]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [58]:
#importing library
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,FunctionTransformer
import numpy as np

In [48]:
#data load

In [49]:
df = pd.read_csv("insurance (1).csv")

In [50]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df.shape

(1338, 7)

In [9]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
df = df.drop_duplicates()

In [13]:
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   object
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   object
 5   region    1337 non-null   object
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 83.6+ KB

In [16]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

In [26]:
#apply min max scaler
minmax = MinMaxScaler()
df1["bmi"] = minmax.fit_transform(df1[["bmi"]])

In [28]:
df1.head()

   age     sex       bmi  children smoker     region      charges
0   19  female  0.321227         0    yes  southwest  16884.92400
1   18    male  0.479150         1     no  southeast   1725.55230
2   28    male  0.458434         3     no  southeast   4449.46200
3   33    male  0.181464         0     no  northwest  21984.47061
4   32    male  0.347592         0     no  northwest   3866.85520

In [29]:
df1["bmi"].min()

np.float64(0.0)

In [30]:
df1["bmi"].max()

np.float64(1.0)

In [33]:
# by changing default
minmx = MinMaxScaler(feature_range=(1,5))

In [34]:
#fit
df1["charges"] = minmx.fit_transform(df1[["charges"]])
df1.head()

   age     sex       bmi  children smoker     region   charges
0   19  female  0.321227         0    yes  southwest  2.006443
1   18    male  0.479150         1     no  southeast  1.038544
2   28    male  0.458434         3     no  southeast  1.212461
3   33    male  0.181464         0     no  northwest  2.332040
4   32    male  0.347592         0     no  northwest  1.175262

In [35]:
df1["charges"].max()

np.float64(5.0)

In [44]:
# do for standard scaler

In [62]:
#log transform
ft = FunctionTransformer(np.log1p)

In [53]:
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [63]:
df2= ft.fit_transform(df2[["charges"]])
df2.head()

    charges
0  9.734236
1  7.453882
2  8.400763
3  9.998137
4  8.260455